modLoader = "javafml"
loaderVersion = "[41,)"
license = "GPL-3.0"

[[mods]]
modId = "iconr"
version = "${version}"
displayName = "Icon Renderer"
# displayURL="https://changeme.dev/" #optional
# logoFile="icon.png" #optional
credits = "GregTaoo, pkstDev" #optional
authors = "TexTrue, BocchiKessokuTeam, TexTrueStudio" #optional
description = '''
Icon Renderer re-ported to Forge 1.19.x .
'''

[[dependencies.iconr]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iconr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
